### ISSUE TITLE
OnePole renamed?

### ISSUE THREAD

**Issue by gitelope** [LancePutnam/Gamma#14]
from the Google doc:

OnePole - one-pole smoothing LPF.  Couldn’t you also have a one pole HPF?  If so, then that should be specified in the name.
Suggested name: Lowpass, SimpleLowpass, Smoothing
Matt suggests:  OnePoleLPF
LJP: Yes, it could be either high- or low-pass. The same with a one-zero filter. How could we logically name all these possible filters? LPF1p, LPF1z, HPF1p, HPF1z?
DA: the documentation claims it is a smoothing filter.  That makes it LP only, no? Maybe I am misinterpreting your response.  
I like OnePoleLPF.  LPF1p strikes me as awkward. Why not LP, LPF, or Lowpass?   We have no other classes of similar name.

**Comment by sabjorn** [comment]
this issue is solved?

https://github.com/LancePutnam/Gamma/blob/2afdd947119418c6c7db939d6d792fc8e709892b/Gamma/Filter.h#L548

OnePole is lowpass or highpass

**Comment by LancePutnam** [comment]
Yes, the current version supports high-pass (db7d973ffeba2306cacf7e62eae761c3c3b25545).
