### ISSUE TITLE
LFO Line2 Mod Errors

### ISSUE THREAD

**Issue by mhetrick** [LancePutnam/Gamma#31]
The Line2() output for the LFO class behaves incorrectly with mod values >.98 and <.02. Behavior should be predictable for all values -1 to +1.

**Comment by LancePutnam** [comment]
Looks okay to me for all values except possibly mod=1 where the ramp flips from up to down. Is this what you are observing?

**Comment by mhetrick** [comment]
After further testing, yes, that's the issue that we were observing. The other values were issues with our visualizer code.

**Comment by LancePutnam** [comment]
I'll close this issue then. I also think mod values should be "periodic" so that 0 and 1 produce the same waveform (but that would be better opened as another issue).
