### ISSUE TITLE
STFT 

### ISSUE THREAD

**Issue by NicolasDC** [LancePutnam/Gamma#33]
Eventually , after several minutes, STFT in MAG_FREQ or MAG_PHASE , collects artifacts and corrupt buffers (bins auxs)  and reset phases method no work at all.

**Comment by LancePutnam** [comment]
Thanks for the report. Could you describe what the settings were for the STFT (window size, hop size, pad size, window type, num aux)? Also, a minimal code snippet that produces the problem would be extremely helpful.

**Comment by LancePutnam** [comment]
This appears to be the same issue as #45
