### ISSUE TITLE
segExp.cpp example code is outdated

### ISSUE THREAD

**Issue by enclle** [LancePutnam/Gamma#47]
Hello,

Trying to compile the examples, make examples/ * / *.cpp, it stops at segExp.cpp example (from examples/envelop), first complaining about ../examples.h not found, after copying examples.h from examples/synths to examples, and running make again, it complains about RUN_AUDIO_MAIN.
As I couldn't figure out what is RUN_AUDIO_MAIN, I copied the "boilerplate" code from other example and updated it, see the attached file.

Please correct the segExp.cpp example, if you want, just replace it with the one attached (if it's correct...).
The attached file [segExp.cpp.txt](https://github.com/LancePutnam/Gamma/files/710185/segExp.cpp.txt) has the .txt extension because GitHub "doesn't support" .cpp.

**Comment by LancePutnam** [comment]
Thanks, missed that one somehow...
